### ISSUE TITLE
Fix link to python file

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccd-reduction-and-photometry-guide#230]
See https://github.com/mwcraig/ccd-reduction-and-photometry-guide/pull/209#pullrequestreview-370062661

**Comment by morrme** [comment]
@mwcraig 
Clicking on  the image_sim.py link on https://github.com/mwcraig/ccd-reduction-and-photometry-guide/blob/master/notebooks/01-04-Nonuniform-sensitivity.ipynb

 takes me directly to https://render.githubusercontent.com/view/image_sim.py . 

What is the desired result?

**Comment by mwcraig** [comment]
@morrme -- thanks for reporting this. I think that is the intended behavior for now. As of last summer there wasn't a good way to link to a Python file from a notebook. That seemed odd to me and it may have been fixed.
