### ISSUE TITLE
 `trimmed_bias.dtype = 'float32'`  is broken in discussion of making files smaller

### ISSUE THREAD

**Issue by jpmorgen** [astropy/ccd-reduction-and-photometry-guide#236]
What works:

trimmed_bias.data = trimmed_bias.data.astype('float32')

Great idea, though! Would be nice to have some sort of option to set property in CCDData to do this automatically when writing files.

jpm

**Comment by mwcraig** [comment]
Thanks, fixed version will be online shortly.
