### ISSUE TITLE
Issue on page /notebooks/01-03-Construction-of-an-artificial-but-realistic-image.html

### ISSUE THREAD

**Issue by Logic-Beach** [astropy/ccd-reduction-and-photometry-guide#317]
I'm not quite sure what is meant here:
`The Python file referenced below, convenience_functions.py, contains a few functions for convenient display of images in a notebook. Note that by clicking the above link you can read (or edit) the file in the browser.`

I get an error trying to import `convenience_functions`
`ModuleNotFoundError: No module named 'convenience_functions'`

The text references a "link" but I see no link, am I missing something?
<img width="719" alt="Screen Shot 2022-01-04 at 5 52 29 PM" src="https://user-images.githubusercontent.com/43481545/148139499-b47ab391-55b0-41c4-b6e7-9693259f64a8.png">

**Comment by programatt** [comment]
If you're running the jupyter notebook from the root of the repository or a parent of the repository the imports should work ok. The file you're looking for is https://github.com/astropy/ccd-reduction-and-photometry-guide/blob/main/notebooks/convenience_functions.py

**Comment by mwcraig** [comment]
@Logic-Beach  -- thank you for reporting this. I'll try to get an easier-to-use link in the next bugfix edition.

@programatt  -- thanks for providing the link!

**Comment by mwcraig** [comment]
Related to #230

**Comment by mwcraig** [comment]
Fixing shortly -- how would you like to be listed in the credits @Logic-Beach?
