### ISSUE TITLE
Issue on page /notebooks/01-06-Image-combination.html

### ISSUE THREAD

**Issue by Logic-Beach** [astropy/ccd-reduction-and-photometry-guide#318]
There appears to be an issue when using this function in the image reduction example:

<img width="639" alt="Screen Shot 2022-01-04 at 8 49 04 PM" src="https://user-images.githubusercontent.com/43481545/148152978-bfb4ccdf-006a-4c6d-b731-f6c17e91817e.png">

**Comment by richardhendricks** [comment]
The os.getenv command will return None if there is not a GUIDE_RANDOM_SEED environment variable. Try setting that in your environment, or change the None to something appropriate.

**Comment by mwcraig** [comment]
Thanks for opening this -- I have a fix I need to get merged.

**Comment by mwcraig** [comment]
This is fixed in the latest version, available at http://www.astropy.org/ccd-reduction-and-photometry-guide/v/dev/notebooks/00-00-Preface.html (if you are reading it) or by cloning this repository.

Closed by #315
