### ISSUE TITLE
Wrong equation when explaining the MAD

### ISSUE THREAD

**Issue by nicocardiel** [astropy/ccd-reduction-and-photometry-guide#324]
I think there is a mistake in the 01-06-Image-combination.ipynb notebook when explaining how the median absolute deviation is computed. The quoted equation:

$$
MAD = \frac{1}{N}\sum_{i=0}^N |x_i - \text{median}(x)|.
$$

is computing the mean (not de median) of the $x_i - \text{median}(x)$ values. The correct expression should be

$$
\text{MAD} = \text{median}\big( x_i - \text{median}(x)\big )
$$

**Comment by mwcraig** [comment]
@nicocardiel  -- thanks for catching this! Would you be willing to open a small pull request to fix this? If you haven't used git/github much you could do this change in your browser: go to https://github.com/astropy/ccd-reduction-and-photometry-guide/blob/main/notebooks/01-06-Image-combination.ipynb, click the pencil icon to edit, and make the change. Then click the green button at the bottom, selecting the option to option to make a new branch if it is offered. After that there is is one more green button to push, to open a pull request.

If you would prefer that I make the change just let me know (and apologies if the instructions were unnecessary -- I've been trying to make it easier for folks to contribute).

**Comment by mwcraig** [comment]
Closed by #327
