### ISSUE TITLE
Issue on page /search.html

### ISSUE THREAD

**Issue by sarallelagram** [astropy/ccd-reduction-and-photometry-guide#328]
Hello! The guide refers to a "convenience_functions.py" file several times, but in the place it mentions it is available for download, there is no live link. (It isn't catastrophic, I've directed students to imshow instead). Happy to help update if that's useful.

**Comment by mwcraig** [comment]
@sarallelagram -- if you are willing to add a link to the file that would be great. I could (in addition) package this repo so it can be pip or conda/mamba installed if that would also be helpful.

**Comment by mwcraig** [comment]
A bunch of people have asked about the link so I've fixed it in #334
