### ISSUE TITLE
Issue on page /notebooks/01-03-Construction-of-an-artificial-but-realistic-image.html

### ISSUE THREAD

**Issue by DomenicoMura** [astropy/ccd-reduction-and-photometry-guide#332]
First of all, great work!
I just cannot find the link to convenience_functions.py, hence I am not able to use show_image.
Thanks!

**Comment by mwcraig** [comment]
@DomenicoMura -- thanks for the feedback, and sorry for the delay. One solution is to grab a copy of the zip file [here](https://github.com/astropy/ccd-reduction-and-photometry-guide/releases/tag/2.0.0) (just made this) and grab the function from there. I'll try to get a better download link integrated into the guide.
