### ISSUE TITLE
Multiple missing files

### ISSUE THREAD

**Issue by qiushitian** [astropy/ccd-reduction-and-photometry-guide#342]
[/notebooks/01-08-Overscan.html](https://www.astropy.org/ccd-reduction-and-photometry-guide/v/dev/notebooks/01-08-Overscan.html) is missing `dark-test-0002d1000.fit.bz2` and

[/notebooks/02-01-overscan-trimming-and-bias-subtraction-background.html](https://www.astropy.org/ccd-reduction-and-photometry-guide/v/dev/notebooks/02-01-overscan-trimming-and-bias-subtraction-background.html) is missing `single_bias_thermoelectric.fit.bz2`

[`notebooks/download_data.py`](https://github.com/astropy/ccd-reduction-and-photometry-guide/blob/main/notebooks/download_data.py) is supposed to download them. I tested that the Zenodo links work fine. Something prevented downloading?

**Comment by mwcraig** [comment]
Thanks for reporting this @qiushitian! I tried `download_data.py` locally this morning and it seemed to download everything, so I'm hoping this was an intermittent connection problem or something. 

Could you please try downloading again and report back either way whether it succeeds or fails?

**Comment by mwcraig** [comment]
Closing, but please let me know if you are still having this issue
